spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: service1
          uri: http://localhost:1111/
          predicates:
          - Path=/service1/**
        - id: service2
          uri: http://localhost:2222/
          predicates:
          - Path=/service2/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka